-- Création de la table pour stocker les opportunités d'arbitrage
create table if not exists public.opportunities (
    id bigint generated by default as identity primary key,
    group_id text unique not null,
    created_at timestamptz default now(),
    data jsonb not null  -- Stocke toute la structure JSON originale
);

-- Index sur group_id pour les recherches rapides
create index if not exists opportunities_group_id_idx on public.opportunities(group_id);

-- Index GIN sur les données JSON pour les recherches dans la structure
create index if not exists opportunities_data_idx on public.opportunities using gin (data);

-- Politiques de sécurité Row Level Security (RLS)
alter table public.opportunities enable row level security;

-- Permettre l'insertion et la lecture pour les utilisateurs authentifiés
create policy "Enable insert for authenticated users only"
on public.opportunities for insert
to authenticated
with check (true);

create policy "Enable read access for authenticated users only"
on public.opportunities for select
to authenticated
using (true);